### ISSUE TITLE
Inconsistent `JSON.GET`: The output isn't matching with redis

### ISSUE THREAD

**Issue by shashi-sah2003** [DiceDB/dice#1278] opened 2024-11-13 09:36 UTC
## Steps to reproduce

1. JSON.SET doc $ '{"a":2, "b": 3, "nested": {"a": 4, "b": null}}'
2. JSON.GET doc $..b
3. JSON.GET doc ..a $..b

## Expected output

![image](https://github.com/user-attachments/assets/2977464d-04b4-4066-8cc4-11b94e29021f)
![image](https://github.com/user-attachments/assets/06ac8ef5-1f84-46e8-95d0-90e9fd816ab7)
![image](https://github.com/user-attachments/assets/22ac9e55-056c-48e3-b5eb-dd3b09884522)

The expected output when the above set of commands when run on Redis

## Observed output

![image](https://github.com/user-attachments/assets/dac4ca11-298b-43c3-90b4-1ec0e41fc149)

The observed output when the above set of commands when run on DiceDB

The steps to run the test cases are mentioned in the README of the [dice-tests repository](https://github.com/AshwinKul28/dice-tests).

## Expectations for resolution

This issue will be considered resolved when the following things are done

1. changes in the [`dice`](https://github.com/dicedb/dice) code to meet the expected behavior
4. Successful run of the tcl test behavior

You can find the tests under the `tests` directory of the [`dice`](https://github.com/dicedb/dice) repository and the steps to run are in the [README file](https://github.com/dicedb/dice). Refer to the following links to set up DiceDB and Redis 7.2.5 locally

- [setup DiceDB locally](https://github.com/dicedb/dice)
- [setup Redis 7.2.5 locally](https://gist.github.com/arpitbbhayani/94aedf279349303ed7394197976b6843)
- [setup DiceDB CLI](https://github.com/dicedb/dice)

**Comment by shashi-sah2003** [comment] 2024-11-13 09:37
@JyotinderSingh @lucifercr07 @apoorvyadav1111 I can work on this issue. 
thanks

**Comment by JyotinderSingh** [comment] 2024-11-14 02:32
> @JyotinderSingh @lucifercr07 @apoorvyadav1111 I can work on this issue. 
> 
> thanks

Thanks for taking this up, assigned

**Comment by apoorvyadav1111** [comment] 2024-11-14 03:45
Hi, this issue is a duplicate of #1002, please comment on the issue. Closing as duplicate.

**Comment by apoorvyadav1111** [comment] 2024-11-14 03:46
duplicate of #1002

**Closed** 2024-11-14 03:46 UTC
