### ISSUE TITLE
Dockerfile for this project

### ISSUE THREAD

**Issue by amandesai01** [DiceDB/dice#47] opened 2022-10-20 12:21 UTC
**Is your feature request related to a problem? Please describe.**
This is a relatively new project and I guess it would be nice if we can make it easier for people to play-around. Docker image will let people do that.

**Describe the solution you'd like**
Creating a Dockerfile with linux image as base.

I would love to take this up, won't be a huge task.

**Comment by santhosh-chinnasamy** [comment] 2022-10-21 16:34
@amandesai01
- duplicate of #14
- a PR is already there #15 maybe you can test/review it.

**Closed** 2024-07-31 13:27 UTC
