### ISSUE TITLE
Connecting to DiceDB server again, does not work

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#196] opened 2024-08-01 18:26 UTC
I am using the DiceDB server on my local machine and connecting it with the DiceDB CLI.
Connecting once to the server works fine, but if I try to connect it again after I exit the CLI, the CLI never connects and the server hangs.

**How to reproduce**

1. Start DiceDB Server
2. Connect to the server using DiceDB CLI
3. fire command `SET mykey "Hello, World!"`
4. fire command `GET mykey`
5. fire command `exit`

This will exit the CLI with a `Goodbye!` message.

6. Connect to the server using DiceDB CLI, again.

This never completes and the CLI hangs. 
![image](https://github.com/user-attachments/assets/f27b4211-9efc-4a3f-9b21-75a72ebb212b)

Also, after hitting `CTRL+C` several times, the CLI finally finishes with error

```

^CTraceback (most recent call last):
  File "/home/arpit/dicedb/dice/pulumi/venv/bin/dice", line 8, in <module>
    sys.exit(main())
  File "/home/arpit/dicedb/cli/dice/entry.py", line 471, in main
    client = create_client(ctx.params)
  File "/home/arpit/dicedb/cli/dice/entry.py", line 440, in create_client
    return Client(
  File "/home/arpit/dicedb/cli/dice/client.py", line 97, in __init__
    self.connection.connect()
  File "/home/arpit/dicedb/dice/pulumi/venv/lib/python3.10/site-packages/redis/connection.py", line 289, in connect
    self.on_connect()
  File "/home/arpit/dicedb/dice/pulumi/venv/lib/python3.10/site-packages/redis/connection.py", line 391, in on_connect
    self.read_response()
  File "/home/arpit/dicedb/dice/pulumi/venv/lib/python3.10/site-packages/redis/connection.py", line 512, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/home/arpit/dicedb/dice/pulumi/venv/lib/python3.10/site-packages/redis/_parsers/resp2.py", line 15, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
  File "/home/arpit/dicedb/dice/pulumi/venv/lib/python3.10/site-packages/redis/_parsers/resp2.py", line 25, in _read_response
    raw = self._buffer.readline()
  File "/home/arpit/dicedb/dice/pulumi/venv/lib/python3.10/site-packages/redis/_parsers/socket.py", line 115, in readline
    self._read_from_socket()
  File "/home/arpit/dicedb/dice/pulumi/venv/lib/python3.10/site-packages/redis/_parsers/socket.py", line 65, in _read_from_socket
    data = self._sock.recv(socket_read_size)
KeyboardInterrupt
```

Bigger issue: The DiceDB server is now unresponsive. Even after hitting `CTRL+C` it does not exit.
The only way to shut down the process is identifying the process listening to this port and killing it.

```
$ sudo netstat -atlpn | grep :7379
$ sudo kill -9 <process_id>
```

![image](https://github.com/user-attachments/assets/4760621f-fffd-409e-a5d8-ea53320d0ecc)

**Comment by cam4phor** [comment] 2024-08-01 18:31
Hi @arpitbbhayani, Can I try to resolve this issue?

**Comment by thisisvk45** [comment] 2024-08-01 19:18
You're having trouble reconnecting to DiceDB using the CLI after exiting. Here’s how to fix it:

Check Server Logs: Look for errors when reconnecting.
Connection Handling: Ensure the server closes connections properly when the client exits.
Client Cleanup: Make sure the CLI client closes the connection before exiting.
Timeouts and Retries: Add timeouts and retry logic in the CLI.
Server Config: Verify server settings to handle multiple connections.

If it still doesn’t work, get more logs and reach out to DiceDB support.

**Comment by arpitbbhayani** [comment] 2024-08-01 19:30
@cam4phor go for it. assigned the issue to you.

**Comment by soumya-codes** [comment] 2024-08-02 08:36
@arpitbbhayani @thisisvk45 I faced this issue yesterday evening and have figured out the issue. The issue is occurring as we are not handling the the `closing of connection from the client side` event, making the DecodeOne() method run in an infinite loop thus making the server irresponsive. Please let me know if you need any help. I have a fix ready.

**Comment by AshwinKul28** [comment] 2024-08-02 10:03
Yup, It's the issue in the function [DecodeOne()](https://github.com/DiceDB/dice/blob/master/core/io.go#L38). I second @soumya-codes . I have also fixed it on my end locally, but please proceed and give a PR @soumya-codes

**Comment by soumya-codes** [comment] 2024-08-02 15:59
@arpitbbhayani can you please assign the issue to me.

**Comment by cam4phor** [comment] 2024-08-02 17:01
@soumya-codes, I have fixed the issue. Will be raising a PR.

**Comment by soumya-codes** [comment] 2024-08-03 11:46
@cam4phor I have left some comments. Please let me know your if you would like to discuss the same.

**Comment by cam4phor** [comment] 2024-08-03 12:36
HI @soumya-codes, Somehow I can't see your comments. Can you please help me with a link or something. Apologies for this :)

**Closed** 2024-08-04 14:32 UTC
Labels: bug, difficulty-level -- mid
