### ISSUE TITLE
Expose Byte-array operations via Dice commands

### ISSUE THREAD

**Issue by yashs360** [DiceDB/dice#177] opened 2024-07-23 11:36 UTC
Dice now supports the Byte Array datatype. Expose the functionality of data type via Dice DB operations / commands.

Example:
https://redis.io/docs/latest/commands/bitcount/

**Comment by MohitVachhani** [comment] 2024-07-23 20:06
In this, we just need to add support for `bitcount` 
<img width="1334" alt="image" src="https://github.com/user-attachments/assets/610ef7ad-9809-4f0c-b025-49873a04b1a4">

Only this for now right ? -> If yes then I can work on this!

**Comment by arpitbbhayani** [comment] 2024-07-24 03:05
@MohitVachhani @yashs360 Isn't this a duplicate of https://github.com/DiceDB/dice/issues/143?

**Closed** 2024-07-24 03:09 UTC

**Comment by yashs360** [comment] 2024-07-24 03:10
Yes, duplicate of #143 . Not sure what i had in mind when i created this.
@MohitVachhani please review #143 , its a few other commands.
